site_name: Duron
site_url: "https://brian14708.github.io/duron"
repo_url: "https://github.com/brian14708/duron"
repo_name: "brian14708/duron"
nav:
  - index.md
  - Reference:
      - reference/duron.md
      - reference/log.md
      - reference/codec.md
      - reference/tracing.md
      - reference/typing.md
  - Trace UI: https://brian14708.github.io/duron/trace-ui/

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
  icon:
    logo: material/head-sync
  features:
    - navigation.tabs
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_source: false
            show_submodules: false
            show_attribute_values: false
            merge_init_into_class: true
            members: true
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://typing-extensions.readthedocs.io/en/latest/objects.inv
  - mermaid2:
      arguments:
        theme: |
          ^(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light'
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
